version: '3.8'

services:
  db:
    container_name: todo-db
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=todo_app_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-backend

volumes:
  postgres_data:


networks:
  todo-backend: